version: '3'

networks:
  php-dev:

services:
  php:
    container_name: php8.2
    image: php:8.2-fpm
    restart: always
    privileged: true
    networks:
      - php-dev
    ports:
      - "9000:9000"
    volumes:
      - "/Users/cisco/Desktop/workspace/PHP/www:/var/www"
  nginx:
    container_name: nginx1.27
    image: nginx:1.27
    privileged: true
    restart: always
    networks:
      - php-dev
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "php"
    volumes:
      - "/Users/cisco/Desktop/workspace/PHP/www:/var/www"
      - "/Users/cisco/Desktop/workspace/docker/docker_data/php_dev/nginx/logs:/var/log/nginx"
  mysql:
    image: mysql:9.1
    container_name: mysql9.1
    privileged: true
    restart: always
    networks:
      - php-dev
    ports:
      - "3306:3306"
    volumes:
      - "/Users/cisco/Desktop/workspace/docker/docker_data/php_dev/mysql/data:/var/lib/mysql"
      - "/Users/cisco/Desktop/workspace/docker/docker_data/php_dev/mysql/log:/var/log/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: redis:7.4
    container_name: redis7.4
    privileged: true
    restart: always
    networks:
      - php-dev
    ports:
      - "6379:6379"
    command: redis-server /usr/local/redis/conf/redis.conf # 启动redis服务并指定配置文件
    volumes:
      - "/Users/cisco/Desktop/workspace/docker/docker_data/php_dev/redis/data:/data" # redis数据目录
      - "/Users/cisco/Desktop/workspace/docker/docker_data/php_dev/redis/conf/redis.conf:/usr/local/redis/conf/redis.conf" #redis配置文件
